src/App.js, src/helpers/auth.js, src/index.js, src/stores/auth/auth-actions.js, src/stores/auth/auth-slice.js, src/stores/index.js
=> feat: set up redux store for auth

package-lock.json, package.json, src/App.js, src/components/ProductCard/ProductCard.js, src/components/ProductDetail/ProductDetail.js, src/components/SVG/email.svg, src/components/SVG/key.svg, src/pages/Auth/Login/Login.js, src/pages/Auth/Login/Login.scss, src/styles/_global.scss, src/styles/_variables.scss
=> feat: Slice Account Login UI

src/App.js, src/index.js, src/middleware/is-guest.js, src/middleware/is-logged-in.js, src/pages/Error/RouteNotFound.js, src/routes/RouteComponent.js, src/routes/routes.js
Prior to this commit, all routes are hard-coded in App.js. This commit move the routes to seperate file and add additional middleware if needed
Fixes #23
=> feat: convert routing system 

src/components/BannerSide/BannerSide.js, src/components/Layout/MainLayout.js, src/components/PopularCategory/PopularCategory.js, src/config/api.js, src/helpers/api/get-home-data.js, src/helpers/api/get-popular-category.js, src/helpers/api/post-login-data.js, src/helpers/api/post-logout-data.js, src/stores/auth/auth-actions.js
=> refactor: move APIs call into separate helper

package-lock.json, package.json, src/index.js
=> fix: correct scroll behavior

src/components/ProductCard/ProductCard.js, src/components/ProductDetail/ProductDetail.js, src/components/ScrollableContainer/ScrollableContainer.js, src/config/api.js, src/helpers/api/get-home-data.js, src/helpers/api/get-popular-category.js, src/helpers/api/get-product-detail.js, src/helpers/api/post-login-data.js, src/helpers/api/post-logout-data.js, src/pages/Product/Detail/Detail.js, src/routes/routes.js
=> feat: call products API by slug name

src/components/BannerCarousel/BannerCarousel.js, src/components/CheckoutProgressBar/CheckoutProgressBar.js, src/components/CheckoutProgressBar/CheckoutProgressBar.scss, src/components/EditAddressModal/EditAddressModal.js, src/components/Navbar/Navbar.js, src/components/ProductCardCart/ProductCardCart.js, src/components/ProductCardCart/ProductCardCart.scss, src/components/ProductDetail/ProductDetail.js, src/components/ProductsSummary/ProductsSummary.js, src/components/ProductsSummary/ProductsSummary.scss, src/components/SVG/location.svg, src/components/ShipmentAddress/ShipmentAddress.js, src/components/ShipmentAddress/ShipmentAddress.scss, src/components/ShoppingPriceSummary/ShoppingPriceSummary.js, src/components/ShoppingPriceSummary/ShoppingPriceSummary.scss, src/config/api.js, src/pages/Checkout/Shipment/Shipment.js, src/routes/routes.js, src/styles/_global.scss, src/styles/_variables.scss
=> feat: slice shipment page

src/helpers/api/get-related-products.js, src/pages/Error/ProductNotFound.js, src/pages/Error/RouteNotFound.js, src/pages/Product/Detail/Detail.js
=> feat: call related product API in product detail

src/components/ShoppingSummaryModal/ShoppingSummaryModal.js
=> feat: display correct info in shopping summary

src/components/Navbar/CategoryDropdown/CategoryDropdown.scss, src/components/Navbar/Navbar.js, src/components/Navbar/Navbar.scss, src/components/Navbar/UserDropdown/UserDropdown.js, src/components/SearchModal/SearchModal.js, src/components/SearchModal/SearchModal.scss, src/styles/_global.scss
=> fix: navbar wrap bug

src/components/Navbar/Navbar.js, src/components/ProductDetail/ProductDetail.js, src/stores/cart/cart-slice.js, src/stores/index.js, src/styles/_global.scss
=> feat: make cart logic in redux

src/components/ProductDetail/ProductDetail.js
=> fix: fix add cart is working when not logged in.

package-lock.json, src/components/Navbar/UserDropdown/UserDropdown.js, src/components/Navbar/UserDropdown/UserDropdown.scss, src/pages/Checkout/CheckoutGateway/CheckoutGateway.js, yarn.lock
=> fix: Fix user dropdown and relocating changed file

src/components/CreateInspireMeModal/CreateForm/CreateForm.js, src/components/CreateInspireMeModal/CreateForm/InspireMeForm.scss, src/components/CreateInspireMeModal/CreateInspireMeModal.js, src/components/CreateInspireMeModal/SelectProducts/SelectProducts.js, src/components/CreateInspireMeModal/SelectProducts/SelectProducts.scss, src/components/InspireMeDetail/InspireMeDetail.js, src/components/InspireMeDetail/InspireMeDetail.scss, src/components/InspireMePost/InspireMePost.js, src/components/InspireMePost/InspireMePost.scss, src/components/Navbar/Navbar.js, src/components/SVG/plus.svg, src/pages/InspireMe/InspireMe.js, src/routes/routes.js, src/styles/_global.scss
=> feat: slice home page for inspire me

.dockerignore, Dockerfile, nginx.conf
=> feat: setup docker settings

src/components/PaymentProofModal/PaymentProofModal.js, src/components/TransactionDetailModal/TransactionDetailModal.js, src/components/User/TransactionCard/TransactionCard.js, src/components/User/TransactionCard/TransactionProductCard/TransactionProductCard.js, src/pages/User/Transaction/Transaction.js
=> fix: Fix issue updating transaction after update

src/components/Navbar/Navbar.js, src/components/User/Sidebar/Sidebar.js, src/pages/User/Profile/Profile.js, src/pages/User/Transaction/Transaction.js
=> Fixing some responsive issue that not correct

src/pages/Product/List/ProductList.js
=> Fixing product list category that didn't showed.

src/components/Breadcrumb/Breadcrumb.js, src/components/Navbar/Navbar.js, src/components/Navbar/Search/Search.js, src/components/Navbar/Search/Search.scss, src/components/SearchModal/SearchModal.js, src/components/SearchModal/SearchModal.scss, src/helpers/api/get-products.js, src/hooks/use-products-search.js, src/pages/InspireMe/InspireMe.js, src/pages/Product/Detail/Detail.js, src/pages/Product/List/ProductList.js, src/stores/auth/auth-actions.js
=> feat: implements text search

src/components/PopularCategory/PopularCategory.js, src/components/PopularCategory/PopularCategoryCard/PopularCategoryCard.js, src/components/PopularCategory/PopularCategoryCard/PopularCategoryCard.scss
=> fix: fix popular categories image and redirect

src/components/MixAndMatchCanvas/MixAndMatchCanvas.scss
=> fix: change invalid cursor for mix and match

src/App.js, src/routes/routes.js
=> refactor: split code for optimizing

src/components/Footer/Footer.js, src/pages/PrivacyPolicy/PrivacyPolicy.js, src/routes/routes.js
=> feat: create Privacy and Policy

src/components/Breadcrumb/Breadcrumb.js, src/components/Navbar/Navbar.js, src/components/Navbar/Search/Search.js, src/components/Navbar/Search/Search.scss, src/components/SVG/camera.svg, src/components/VisualSearchModal/VisualSearchModal.js, src/components/VisualSearchModal/VisualSearchModal.scss, src/helpers/api/search-by-image.js, src/pages/Product/List/ProductList.js, src/pages/User/Transaction/Transaction.js, src/pages/VisualSearch/VisualSearch.js, src/pages/VisualSearch/VisualSearch.scss, src/routes/routes.js
=> feat: implements visual search

src/components/InspireMeDetail/InspireMeDetail.js, src/helpers/api/inspire-me/get-inspire-me-posts.js, src/pages/InspireMe/InspireMe.js
=> feat: add pagination to inspire me

src/components/ProductDetail/ProductDetail.js, src/components/ProductDetail/ProductDetail.scss, src/components/ScrollableContainer/ScrollableContainer.scss, src/pages/Product/Detail/Detail.js, src/pages/Product/Detail/Detail.scss, src/styles/_global.scss, src/styles/_variables.scss
=> feat: Slice new product detail page

src/components/ProductDetail/ProductDetail.js, src/stores/cart/cart-actions.js
=> feat: Integrate new product detail page with backend

src/components/CartItem/CartItem.js, src/components/CartSelector/CartSelector.js, src/components/Footer/Footer.js, src/components/Footer/Footer.scss, src/components/InspireMePost/InspireMePost.js, src/components/InspireMePost/InspireMePost.scss, src/components/InspireMePost/Placeholder/Placeholder.js, src/components/ItemsSummary/ItemsExpeditionSummary.js, src/components/Navbar/CategoryDropdown/CategoryDropdown.scss, src/components/ProductCard/ProductCard.js, src/components/ProductCard/ProductCard.scss, src/components/ProductDetail/ProductDetail.js, src/components/ProductDetail/ProductDetail.scss, src/components/ShoppingSummaryModal/ShoppingSummaryModal.js, src/components/TransactionDetailModal/TransactionDetailModal.js, src/components/User/TransactionCard/TransactionCard.js, src/components/User/TransactionCard/TransactionCard.scss, src/pages/Checkout/Shipment/Shipment.js, src/pages/Home.js, src/pages/Product/Detail/Detail.js, src/pages/User/Transaction/Transaction.js
=> feat: match interface with new UI UX design

src/components/MixAndMatchCanvas/MixAndMatchCanvas.js, src/components/MixAndMatchMenu/MixAndMatchMenu.js
=> Implement new API update on Mix & Match.

src/pages/Home.js
=> feat: limit "Model Busana Favorit" to 4 products

src/components/PopularCategory/PopularCategory.js
=> fix: undefined category in popular category

src/components/ProductDetail/ProductDetail.js
=> fix: fix extra 0 on price label in product detail

src/components/Navbar/NavDropdown/NavDropdown.js, src/components/Navbar/UserDropdown/UserDropdown.js, src/components/Navbar/UserDropdown/UserDropdown.scss
=> feat: make item on user dropdown left aligned

src/components/PopularCategory/PopularCategory.js, src/pages/Auth/Register/Register.js
=> feat: auto logged in when finished registering
